### Get tokens/login
POST http://localhost:5000/api/auth
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

### Get user
GET http://localhost:5000/api/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE2NDg3NjYyLCJleHAiOjE2MTcwODc2NjJ9.YYqkdcgCAUKWBrV3wixbHNaHLkF8EA3wzppXGEnkUeg

### Refresh token
POST http://localhost:5000/api/auth/token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE2NDg3NTc3fQ.Wgpxe4cNbZVTwrn6Gh4e3HW6w4PS8xD7Zai94dWZElU"
}

### Logout
POST http://localhost:5000/api/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE2NDg3NTc3fQ.Wgpxe4cNbZVTwrn6Gh4e3HW6w4PS8xD7Zai94dWZElU"
}

### Change credentials
POST http://localhost:5000/api/auth/updateCredentials
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE2NDg3NzgwLCJleHAiOjE2MTcwODc3ODB9.7JmSBoQ_XulUWIGjNbdlXoFTfw3dECeQbG9I8JyKJdo
Content-Type: application/json

{
    "newUsername": "admin",
    "oldPassword": "admin",
    "oldPassword": "admin",
}

### Get gateways
GET http://localhost:5000/api/gateway
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE2NDg3NzgwLCJleHAiOjE2MTcwODc3ODB9.7JmSBoQ_XulUWIGjNbdlXoFTfw3dECeQbG9I8JyKJdo

