### Get tokens/login
POST http://localhost:5000/api/auth
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

### Get user
GET http://localhost:5000/api/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE2NDg3NjYyLCJleHAiOjE2MTcwODc2NjJ9.YYqkdcgCAUKWBrV3wixbHNaHLkF8EA3wzppXGEnkUeg

### Refresh token
POST http://localhost:5000/api/auth/token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE2NDg3NTc3fQ.Wgpxe4cNbZVTwrn6Gh4e3HW6w4PS8xD7Zai94dWZElU"
}

### Logout
POST http://localhost:5000/api/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE2NDg3NTc3fQ.Wgpxe4cNbZVTwrn6Gh4e3HW6w4PS8xD7Zai94dWZElU"
}

### Change credentials
POST http://localhost:5000/api/auth/updateCredentials
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE2NDg3NzgwLCJleHAiOjE2MTcwODc3ODB9.7JmSBoQ_XulUWIGjNbdlXoFTfw3dECeQbG9I8JyKJdo
Content-Type: application/json

{
    "newUsername": "admin",
    "oldPassword": "admin",
    "oldPassword": "admin",
}

### Get gateways
POST http://localhost:5000/api/gateway
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE3MTEzNDA3LCJleHAiOjE2MTcxMjg0MDd9.EnubMcYLmtrITq_hSvcaK-n3Iur44giyQA0TsfiMEmw
Content-Type: application/json

{
    "order": "asc",
    "rowsPerPage": 5,
    "page": 1,
    "column": "protocol_ver"
}

### Get count of gateways
GET http://localhost:5000/api/gateway
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE3MTEzNDA3LCJleHAiOjE2MTcxMjg0MDd9.EnubMcYLmtrITq_hSvcaK-n3Iur44giyQA0TsfiMEmw

### Get gateway detail
POST http://localhost:5000/api/gateway/detail
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE3NDM5MDc4LCJleHAiOjE2MTc0NDQwNzh9.9tFibqt0nQVwBqo-P1aMVaYJzUSrOHAT89RToV5AEqs
Content-Type: application/json

{
    "devId": 1
}

### Get uplink messages 
POST http://localhost:5000/api/messages/uplink
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE3NTI5NjE3LCJleHAiOjE2MTc1MzQ2MTd9.r5TVVBaEcaNa1RSCGsMvG-eAb9QbxDZK1XVMesIvqTk
Content-Type: application/json

{
    "order": "asc",
    "rowsPerPage": 5,
    "page": 1,
    "column": "id"
}

### Get count of gateways
GET http://localhost:5000/api/messages/uplink
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE3NTM1MDk3LCJleHAiOjE2MTc1NDAwOTd9.jBQEE7TPs5gOQWxJCw4mno5x2OVedNwY-AmGtQePySw


### Get scheduled/sent downlink messages 
POST http://localhost:5000/api/messages/downlink
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE3NTQyMzE4LCJleHAiOjE2MTc1NDczMTh9.xN2SoGb8rQBqa-56apGnKPwaxkpWMV-wZJBwRVOLt9k
Content-Type: application/json

{
    "order": "asc",
    "rowsPerPage": 5,
    "page": 1,
    "column": "id",
    "sent": true
}

### Get count of sent donwlink messages
GET http://localhost:5000/api/messages/downlink/sent
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE3NTQyMzE4LCJleHAiOjE2MTc1NDczMTh9.xN2SoGb8rQBqa-56apGnKPwaxkpWMV-wZJBwRVOLt9k

### Get count of scheduled donwlink messages
GET http://localhost:5000/api/messages/downlink/scheduled
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE3NTQyMzE4LCJleHAiOjE2MTc1NDczMTh9.xN2SoGb8rQBqa-56apGnKPwaxkpWMV-wZJBwRVOLt9k

### Get uplink messages for gateway
POST http://localhost:5000/api/gateway/uplinkMessages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE3NTQ5NTgzLCJleHAiOjE2MTc1NTQ1ODN9.35XG8EblO2vReJvtMC4pfrku0WTFjvzlM4p0WMWAgcI
Content-Type: application/json

{
    "order": "asc",
    "rowsPerPage": 5,
    "page": 1,
    "column": "snr",
    "gatewayId": "111111"
}

### Get count of uplink messages for gateway
POST http://localhost:5000/api/gateway/uplinkMessages/count
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE3NTUwMDE5LCJleHAiOjE2MTc1NTUwMTl9.sWm4sqlQjiCYpQMgM30zhzCWOXCkHl0rIV1YYORUa14
Content-Type: application/json

{
    "gatewayId": "111111"
}

### Get count of sent/scheduled downlink messages for gateway
POST http://localhost:5000/api/gateway/downlinkMessages/count
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE4MTM2NjY5LCJleHAiOjE2MTgxNDE2Njl9.4tdm9a41g5byskehzfapdd-cVzuATroehFKu5utDp3A
Content-Type: application/json

{
    "gatewayId": "111111",
    "sent": true
}

### Get scheduled/sent downlink messages for gateway
POST http://localhost:5000/api/gateway/downlinkMessages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE3NjEwNTg3LCJleHAiOjE2MTc2MTU1ODd9.XP0QZbAVHpe0uvpxQ_rjW9Si_W3SZBeeV5Y9QwougWg
Content-Type: application/json

{
    "order": "desc",
    "rowsPerPage": 5,
    "page": 1,
    "column": "sent",
    "sent": true,
    "gatewayId": "111111"
}


### Get devices
POST http://localhost:5000/api/device
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE4MTMzOTI3LCJleHAiOjE2MTgxMzg5Mjd9.JYW59Ru6W92JKFwgCYcq7ry1dET_NuhQgDqdpFwXOMo
Content-Type: application/json

{
    "order": "asc",
    "rowsPerPage": 5,
    "page": 1,
    "column": "name"
}

### Get count of devices
GET http://localhost:5000/api/device
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE4MTI4NzgzLCJleHAiOjE2MTgxMzM3ODN9.4WzAPw6hrqEmzqie16LRo8LfOStxwwvlp-sexOyZI8c
Content-Type: application/json

### Get device detail
POST http://localhost:5000/api/device/detail
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE4MTM2NjY5LCJleHAiOjE2MTgxNDE2Njl9.4tdm9a41g5byskehzfapdd-cVzuATroehFKu5utDp3A
Content-Type: application/json

{
    "devId": 1
}

### Get uplink messages for device
POST http://localhost:5000/api/device/uplinkMessages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE4MTM2NjY5LCJleHAiOjE2MTgxNDE2Njl9.4tdm9a41g5byskehzfapdd-cVzuATroehFKu5utDp3A
Content-Type: application/json

{
    "order": "asc",
    "rowsPerPage": 5,
    "page": 1,
    "column": "snr",
    "deviceId": "xb15"
}

### Get count of uplink messages for device
POST http://localhost:5000/api/device/uplinkMessages/count
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE4MTM2NjY5LCJleHAiOjE2MTgxNDE2Njl9.4tdm9a41g5byskehzfapdd-cVzuATroehFKu5utDp3A
Content-Type: application/json

{
    "deviceId": "xb15"
}

### Get count of sent/scheduled downlink messages for device
POST http://localhost:5000/api/device/downlinkMessages/count
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE4MTQyMTQzLCJleHAiOjE2MTgxNDcxNDN9.8aSEve8-O4pztyuv7IRSCS7UqtDiGCcrrCJaeoybBUA
Content-Type: application/json

{
    "deviceId": "01fU",
    "sent": false 
}

### Get scheduled/sent downlink messages for device
POST http://localhost:5000/api/device/downlinkMessages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE4MTM2NjY5LCJleHAiOjE2MTgxNDE2Njl9.4tdm9a41g5byskehzfapdd-cVzuATroehFKu5utDp3A
Content-Type: application/json

{
    "order": "desc",
    "rowsPerPage": 5,
    "page": 1,
    "column": "sent",
    "sent": true,
    "deviceId": "xb15"
}

### Get applications
POST http://localhost:5000/api/application
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE4MTcxMzQxLCJleHAiOjE2MTgxNzYzNDF9.6gaBbD1W4NynSbGFD-HH-xiv2ZeIGHI1quxuf_1jQpk
Content-Type: application/json

{
    "order": "desc",
    "rowsPerPage": 5,
    "page": 1,
    "column": "name"
}

### Get application detail
POST http://localhost:5000/api/application/detail
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE4MjA5Nzg3LCJleHAiOjE2MTgyMTQ3ODd9.HnFQbWI0i-7QC5i1-lm9aC0gsFWrj7ojCRu-gq-O8wg
Content-Type: application/json

{
    "applicationId": 1
}

### Get uplink messages for application
POST http://localhost:5000/api/application/uplinkMessages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE4MjA5Nzg3LCJleHAiOjE2MTgyMTQ3ODd9.HnFQbWI0i-7QC5i1-lm9aC0gsFWrj7ojCRu-gq-O8wg
Content-Type: application/json

{
    "order": "asc",
    "rowsPerPage": 5,
    "page": 1,
    "column": "snr",
    "applicationId": 1
}

### Get count of uplink messages for application
POST http://localhost:5000/api/application/uplinkMessages/count
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE4MjA5Nzg3LCJleHAiOjE2MTgyMTQ3ODd9.HnFQbWI0i-7QC5i1-lm9aC0gsFWrj7ojCRu-gq-O8wg
Content-Type: application/json

{
    "applicationId": 1
}


### Get count of sent/scheduled downlink messages for application
POST http://localhost:5000/api/application/downlinkMessages/count
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE4MjA5Nzg3LCJleHAiOjE2MTgyMTQ3ODd9.HnFQbWI0i-7QC5i1-lm9aC0gsFWrj7ojCRu-gq-O8wg
Content-Type: application/json

{
    "applicationId": 1,
    "sent": true
}

### Get scheduled/sent downlink messages for application
POST http://localhost:5000/api/application/downlinkMessages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE4MjA5Nzg3LCJleHAiOjE2MTgyMTQ3ODd9.HnFQbWI0i-7QC5i1-lm9aC0gsFWrj7ojCRu-gq-O8wg
Content-Type: application/json

{
    "order": "desc",
    "rowsPerPage": 5,
    "page": 1,
    "column": "sent",
    "sent": false,
    "applicationId": 2
}