POST http://localhost:5000/api/auth
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###
GET http://localhost:5000/api/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE2NDE4MTcwLCJleHAiOjE2MTY0MTgyMzB9.zKLFh5nO9tqtXqamZbqTVJvxFN0LH9FVama3xYL7n10

###
POST http://localhost:5000/api/auth/token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE2NDE4MTQ5LCJleHAiOjE2MTY1MDQ1NDl9.ZasdrU9BNsqrH8C4fVczImQMaxQk7yLQGRjuqyPlq84"
}

###
POST http://localhost:5000/api/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjE2NDE4MTQ5LCJleHAiOjE2MTY1MDQ1NDl9.ZasdrU9BNsqrH8C4fVczImQMaxQk7yLQGRjuqyPlq84"
}


