export const SET_UPLINK_MESSAGES = "SET_UPLINK_MESSAGES";
export const SET_COUNT_OF_UPLINK_MESSAGES = "SET_COUNT_OF_UPLINK_MESSAGES";
export const RESET_ALL_MESSAGES = "RESET_ALL_MESSAGES";
export const SET_SENT_DOWNLINK_MESSAGES = "SET_SENT_DOWNLINK_MESSAGES";
export const SET_SCHEDULED_DOWNLINK_MESSAGES =
  "SET_SCHEDULED_DOWNLINK_MESSAGES";
export const SET_COUNT_OF_SENT_DOWNLINK_MESSAGES =
  "SET_COUNT_OF_SENT_DOWNLINK_MESSAGES";
export const SET_COUNT_OF_SCHEDULED_DOWNLINK_MESSAGES =
  "SET_COUNT_OF_SCHEDULED_DOWNLINK_MESSAGES";

export const SET_RESULTS = "SET_RESULTS";
export const SET_COUNT_RESULTS = "SET_COUNT_RESULTS";
export const SET_ROWS_PER_PAGE_RESULT = "SET_ROWS_PER_PAGE_RESULT";
export const RESET_RESULTS = "RESET_RESULTS";
export const SELECT_RESULT = "SELECT_RESULT";
export const RESET_SELECTED_RESULT = "RESET_SELECTED_RESULT";
