export const SET_UPLINK_MESSAGES = "SET_UPLINK_MESSAGES";
export const SET_COUNT_OF_UPLINK_MESSAGES = "SET_COUNT_OF_UPLINK_MESSAGES";
export const RESET_ALL_MESSAGES = "RESET_ALL_MESSAGES";
export const SET_SENT_DOWNLINK_MESSAGES = "SET_SENT_DOWNLINK_MESSAGES";
export const SET_SCHEDULED_DOWNLINK_MESSAGES =
  "SET_SCHEDULED_DOWNLINK_MESSAGES";
export const SET_COUNT_OF_SENT_DOWNLINK_MESSAGES =
  "SET_COUNT_OF_SENT_DOWNLINK_MESSAGES";
export const SET_COUNT_OF_SCHEDULED_DOWNLINK_MESSAGES =
  "SET_COUNT_OF_SCHEDULED_DOWNLINK_MESSAGES";
